name: stitch
version: 0.2.0+5
author: Dan Schultz <schultz.t.dan@gmail.com>
description: A pub transformer that generates CSS sprite sheets.
homepage: http://www.github.com/danschultz/stitch
dependencies:
  barback: ^0.15.0
  code_transformers: ^0.2.0
  image: ^1.1.0
  mustache: ^0.1.8
  path: ^1.1.0
  yaml: '>=0.9.0 <3.0.0'
dev_dependencies:
  csslib: ^0.12.0
  guinness: ^0.1.0
  hop: ^0.30.0
  mock: ^0.10.0
  unittest: ^0.10.1
